import { useEffect, useMemo } from "react";
import { Bot } from "lucide-react";
import Card from "../ui/Card.jsx";
import ErrorMessage from "../ui/ErrorMessage.jsx";
import Skeleton from "../ui/Skeleton.jsx";
import useAIAnalysis from "./useAIAnalysis.js";

export default function AIPanel({ title, systemPrompt, buildPrompt, data, fallback }) {
  const { loading, error, response, generate } = useAIAnalysis(systemPrompt, buildPrompt, fallback);
  const signature = useMemo(() => JSON.stringify(data ?? {}), [data]);

  useEffect(() => {
    if (data) generate(data);
  }, [signature]);

  return (
    <Card title={title} kicker="AI Analysis">
      {loading && <Skeleton className="h-32" />}
      {error && <ErrorMessage error={error} context="ai" onRetry={() => generate(data)} compact />}
      {!loading && !error && response && (
        <div className="border border-border bg-panel p-4">
          <div className="mb-3 flex items-center gap-2 text-sm font-semibold text-text">
            <Bot className="h-4 w-4" />
            AI Analysis, powered by Qwen via Hugging Face
          </div>
          <p className="whitespace-pre-line text-sm leading-6 text-text">{response}</p>
        </div>
      )}
      {!response && !loading && !error && <p className="text-sm text-muted">Analysis updates automatically from the current selection.</p>}
      <p className="mt-3 text-xs text-muted">This analysis is generated by AI (Qwen2.5 via Hugging Face) and is intended as a supplementary analytical tool.</p>
    </Card>
  );
}
